apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: morhousjeff/aks-nodejs-argocd
  newTag: 194ef0c297a9d807e9c0abff935a6fb2b9bdd10e
